sudo: required
before_install:
- sudo apt-get install tomcat7
before_script:
- mysql -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('root');"
- nvm ls
- nvm install node
- nvm use node
- npm -v
- node -v
- env
- npm install -g @angular/cli@latest
- npm install -g bower
- npm install @angular/core@latest
- chmod +x ./get_seroUtils.sh
- "./get_seroUtils.sh"
- ls -l ./WebContent/WEB-INF/lib/seroUtils.jar
- cd ./WebContent/resources/app; bower update;
- cd ../../..
- cd ./ScadaLTS-UI
- npm install
- ls -l ./src/app/media
- ng version
- ng build
- cd ./war
- ant war
- ant
- cd ../..
- cd ./ScadaLTS-UI-1
- npm install
- cd ../WebContent/resources/npm/
- npm install
- cd ../../..
language: java
jdk:
- openjdk8
services:
- docker
- mysql
script: ant war && ant junit
branches:
  only:
  - "/^PROC-.*$/"
  - "/^develop-sdtabilit.*$/"
  - "/^#179*$/"
  - "/^master-sdtabilit.*$/"
  - "/^v*$/"
  - "/^develop*$/"
  - "/^master*$/"
notifications:
  email: false
env:
  matrix:
  - CATALINA_HOME=/usr/share/tomcat7
  global:
  - secure: GnCELi5oMHoedyVybTME1gjAcHeqZe0ccJ1A+GnhPdrKMw721ccKVq37NraoSGkxawWiaOSghvMbi4+MI1Vy8VctFY1sKrs+uJ90fELpgkojYQsPMYBrBdT/eicUy2n8ZReGXsj5jbK6Esl1E2mL3BPlMm16tJ/bMV5uw/z3ViMv7Yshs26hZ5ToKc9DAf619N8+jnkCbJj9QD6sjxD49wzetwbCk5hRYaSoHrimuZ9UtPmtwcybf6AnqPHECxHNzm/opIlx//0HWY5SPkSQfN11qUtLZ+5UScAKP1MtRINmKiFFou1S/TdMFDDL5dKhDMjfXeNe+saubPiNsb5Ipj2D/HYdIAZn3/ZINpW3nwJIzw7gp6UvpmOPaAR5ZYedClnnFxwx3YMo9wwTCVIYnN5tLCCzJWhP3eEHhBAUznp2i7L3r4+zqhLaf4OAOhwyKNofrZbLjvjyMwwVGH7NcbYiB4RWcD4RVm/DYSjtc35SScfUCbxZB4pi7HWJbEHooO8ygJ4JuG1O/E0gbUESlZbi+8WpAR6egYjcxraQsUZCabEJZlSMLaXF6T5hr8pYrH7s3g13wWVBgnGzwmjV+M7R9yBVmK6J6y6G6WZYy02Vno29ohFjSqxY+2mQfu73MzcpUk5Q3YijhuSoJ8FL8hoQPCDWiZu10otctx0suZ8=
  - secure: QS2kSguWY3ZOSEbD3Ykfa8I95hRujK0mW/IXKEPV8lpFMsb4PfrCWQGVFUgj6YE8oG9dw1TlS3kX6iW81EkvMmSN4QhiSgn0ejj9zQYCw4AqS1ZXiusW7Ckryw+FyBuKhC6iF+tj9xp3I+WIyndhZ17ye8bDKgOvzygPLzz3p/g/T6TPzXEbuvRssqlughwp13z5cm5kauilJBjT14Lpe+rbBGXYhQPEe2BE8EVSkVj4gOpfMF4a9uy7hS4PpcmbEXZXJ10K61KwZleNPlVP7sj8pCZ74z7hmOnzzmx7Y8u3xaJw5KnsrCCrOCYD0iz2mcQ8KBJksZJukEllP20PpC8QQ8+4mP/EBzAg0WeDZ5RHukx7u4tpl8Qrhsp/zefqp80rMDzhnYx/p+pZk8lSnQ34ZXCLE6QqSz/TYJiGNQt23r+1yALjEATYLD5jM2heMHTTA20SvWWvTM2Ji2IE5UQp7ABzhXTqKVA5BfClFmmVMRi+Q86nl/yMfEJ/lGggpXpofVt2Q5yAdmmsBgcfouOoGwW99k2YDZdAWoo1Fj/rStLtIc71hw1Z0EgARlAcEbCdaFh6w+A+39CCRUq7/6r2+DzEpqFbcEVOKL/K69pDZVQ7aNcgHx7bmlAo5OLNF3q6dCIO1hx1c34apKFN+xSRlV5Yt6vmEmPzxJfzfZw=
after_script:
- wget https://archive.apache.org/dist/tomcat/tomcat-7/v7.0.85/bin/apache-tomcat-7.0.85.tar.gz
- mkdir ./docker/app
- mv apache-tomcat-7.0.85.tar.gz ./docker/app
- ls -l ./docker/app/apache-tomcat-7.0.85.tar.gz
- cd ./docker/app
- echo `pwd`
- echo `ls -l`
- tar -zxvf apache-tomcat-7.0.85.tar.gz
- ls -l
- mv ./apache-tomcat-7.0.85/* ./
- rm -rf ./apache-tomcat-7.0.85
- cp ../../ScadaBR.war ./webapps
- cp ../../ScadaLTS-UI/war/ScadaLTS.war ./webapps
- ls -l ./webapps/ScadaLTS.war
- ls -l ./webapps/ScadaBR.war
- cp ../../WebContent/WEB-INF/lib/mysql-connector-java-3.1.8-bin.jar ./lib/
- cp ../../WebContent/WEB-INF/lib/mysql-connector-java-5.1.38-bin.jar ./lib/
- ls -l ./lib/mysql-connector-java-3.1.8-bin.jar
- ls -l ./lib/mysql-connector-java-5.1.38-bin.jar
- cp -f ../config/context.xml ./conf/
- cat ./conf/context.xml
- cd ../
- pwd
- ls
- docker version
- docker login -u=$DOCKER_USENAME -p=$DOCKER_PASSWORD
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
  fi`
- export IMAGE_NAME=scadalts/scadalts
- docker build -t $IMAGE_NAME:$TRAVIS_COMMIT .
- docker tag $IMAGE_NAME:$TRAVIS_COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME:$TAG
