before_install: 
    - sudo apt-get install tomcat7
before_script:
    - npm install -g bower
    - chmod +x ./get_seroUtils.sh
    - ./get_seroUtils.sh
    - cd ./WebContent/resources/app; bower update;
    - cd ../../..
    - echo $CATALINA_HOME
    - export CATALINA_HOME=/var/lib/tomcat7
    - echo $CATALINA_HOME
language: java
jdk:
    - oraclejdk8
script: ant war
branches:
  only:
    - /^PROC-1-.*$/
notifications:
  email: false
env:
    - CATALINA_HOME=/var/lib/tomcat7