before_install: 
    - sudo apt-get install tomcat7
    - sudo apt-get install nodejs
    - sudo apt-get install npm
before_script:
    - npm install -g bower
    - chmod +x ./get_seroUtils.sh
    - ./get_seroUtils.sh
    - cd ./WebContent/resources/app; bower update;
    - cd ../../..
language: java
jdk:
    - oraclejdk8
script: ant war
branches:
  only:
    - /^PROC-1-.*$/
notifications:
  email: false
env:
    - CATALINA_HOME=/var/lib/tomcat7