sudo: required
before_install:
#- sudo add-apt-repository ppa:openjdk-r/ppa -y
#- sudo apt-get update
#- sudo apt-get install -y openjdk-8-jdk
#- sudo update-alternatives --auto java
#- sudo update-alternatives --auto javac
#- export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
#- java -version
#- javac -version
- sudo apt-get install tomcat7
before_script:
- nvm ls
- nvm install node
- nvm use node
- npm -v
- node -v
- env
- npm install -g @angular/cli
- npm install -g bower
- npm install @angular/core@latest
- chmod +x ./get_seroUtils.sh
- "./get_seroUtils.sh"
- ls -l ./WebContent/WEB-INF/lib/seroUtils.jar
- cd ./WebContent/resources/app; bower update;
- cd ../../..
- cd ./ScadaLTS-UI
- npm install
- ls -l ./src/app/media
- ng build
- cd ./war
- ant war
- cd ../..
language: java
jdk:
- openjdk7
services:
- docker
script: ant war
branches:
  only:
  - "/^PROC-.*$/"
  - "/^develop-sdtabilit.*$/"
  - "/^#179*$/"
notifications:
  email: false
env:
  matrix:
  - CATALINA_HOME=/usr/share/tomcat7
  global:
  - secure: C14HDJPKUumAanXlJtbbA7/54ibtVSURw7lnuxpzBP5k6+pu75P6AixaV81L2RIUUN/eRWcgqpqnor+v6KrZHF/TnOlA5OoS73R+rHy3Rx4B6jzDEHnzyDo00zJGdO9bLOaYfNyqOv8XOtcF2YkenAiPjK/MzsIbObhwicDtREd7Br7ZArBm+GL+c5NQ3e8+gPrt1podg1ldZMbZHAi29vM974etXODsnpA3shIMplVsyxwie4PvgfP1avkeHMuPpflPFX6PrJOWatZvIHLfGqSP/rM51HDgO5xcZ0qDTJOvj7Ko0GHfn0CoWzKhwGrZ1ioRDKmTipFhiqFq7iYLts5eMB03W4m62l2Pxpzbs5ugRC49YtWmvAcbVFzERQg2GlB0/slkSdIwdxGqh8Ec3Ma/vpGNkghBBu/hhC3EladFaHPjcp7jlItW7ktyndikBV1cim95rJWWmuGxk8fOdAEVBuPV0sOx+6AwOSfM+o8Pxbe3Vjqv2UHxmMOLlPBs3uTfeS4awUuRY3oizBxaok+H8XWXMP91CjNStRnPWWIOZGG57QtMDOJiqwdwLENVEasAguwfoKSO2tUToLfHPZxtW86rfoGoX1oQ+JiebONxO5bvony8zqtcCt6s3KesKsQeJJHmfaItxylsQyi072PeDPmVuZDgDSx3C31NCYI=
  - secure: NODnAmr6f++eRo73jznLJphwd58Kva9nXn45/7pmDddVi8akif3tCHDotx1acPwrIiwZDn1WBY7xHAYhuB+vHBep0I0AhHRDKP6q6VuDccK8lMKN11AC0pjXDbJCJOEO6CpRL2TvP/UyOhrmuvihnPqcBU2DX4VLN3cGpW+Jwn38Mk5qhw2RuJV6RFT1+/5XQNvYI3Jyp5jCPwlaCbgV2QKVtVs7NZHrj9U0qfdSsrhxp/3qUh2RrXIYZjVG4KggRWnMQ33BUSVNyDLcrKo++Q0IX5ZRP04j5b9NLvIl2otytEdyBYAa5oQYQMS5X31T9T0RDzVFYRu04HVaOXpfdlg9JdDFWQkVgY+d8ph/ZAX1h39eh3xjmMrUIFvAyQ1Kgawxdy99bYyaEefwDoZLC/O4KNjw84D0oBqTktFg75WsgfqJiUSWbryLnqG389pWGZjykiyfxXQgWF2cpqg76PuZY1gWI0jWBBS0GmrK3DONui3WU/QNcpuJTTOFlC18PC13l3+7mUNSz53BhpJg1Gwk8nUhhSnfin5kafjpUBz6mFGhiGoB46jC//kyAZJ+c+j5k8UKst65EgVp6fbu+JN1QpcDZL9l5r/1UnEQzncMraAGRAUvJL2tMkQmS5gbGwixzcrOdWa61BVs8bWe7eV1twOr2fBUNqHjH32SZYo=
after_script:
# get tomcat7 to ./docker/app
- wget http://ftp.ps.pl/pub/apache/tomcat/tomcat-7/v7.0.76/bin/apache-tomcat-7.0.76.tar.gz
- mkdir ./docker/app
- mv apache-tomcat-7.0.76.tar.gz ./docker/app
- ls -l ./docker/app/apache-tomcat-7.0.76.tar.gz
- cd ./docker/app
- echo `pwd` 
- echo `ls -l`
- tar -xvfz apache-tomcat-7.0.76.tar.gz; ls -l
#- echo $TRAVIS_BUILD_DIR
#- sshpass -e scp ./ScadaBR.war test@149.56.44.225:/home/test/ScadaBR.war
#- sshpass -e scp ./ScadaLTS-UI/war/ScadaLTS.war test@149.56.44.225:/home/test/ScadaLTS.war
