addons:
  ssh_known_hosts: 149.56.44.225
before_install:
#- sudo add-apt-repository ppa:openjdk-r/ppa -y
#- sudo apt-get update
#- sudo apt-get install -y openjdk-8-jdk
#- sudo update-alternatives --auto java
#- sudo update-alternatives --auto javac
#- export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
#- java -version
#- javac -version
- sudo apt-get install tomcat7
- sudo apt-get install traceroute
- sudo apt-get install sshpass
#- wget https://nodejs.org/dist/v6.9.1/node-v6.9.1-linux-x64.tar.xz
#- mkdir node
#- mkdir node/etc
#- echo 'prefix=/usr/local' > node/etc/npmrc
#- tar xvf node-v*.tar.?z --strip-components=1 -C ./node
#- sudo mv node /opt/
#- export PATH=/opt/node/bin:$PATH
#- sudo apt-get install -y build-essential
#- curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
#- sudo apt-get install -y nodejs
#- wget -qO- https://deb.nodesource.com/setup_6.x | sudo bash -
#- sudo apt-get install nodejs
#- sudo apt-get install npm
before_script:
#- export PATH=/opt/node:/opt/node/bin:$PATH
- nvm ls
- nvm install node
- nvm use node
- npm -v
- node -v
- env
- npm install -g bower
- npm install -g angular-cli
- chmod +x ./get_seroUtils.sh
- "./get_seroUtils.sh"
- ls -l ./WebContent/WEB-INF/lib/seroUtils.jar
- cd ./WebContent/resources/app; bower update;
- cd ../../..
- cd ./ScadaLTS-UI
- npm install
- ng build
- cd ./war
- ant war
- cd ../..
language: java
jdk:
- openjdk7
script: ant war
branches:
  only:
  - "/^PROC-.*$/"
  - "/^develop-sdtabilit.*$/"
  - "/SLTS-16.*$/"
  - "/SLTS-26.*$/"
notifications:
  email: false
env:
  matrix:
  - CATALINA_HOME=/usr/share/tomcat7
  global:
  - secure: C14HDJPKUumAanXlJtbbA7/54ibtVSURw7lnuxpzBP5k6+pu75P6AixaV81L2RIUUN/eRWcgqpqnor+v6KrZHF/TnOlA5OoS73R+rHy3Rx4B6jzDEHnzyDo00zJGdO9bLOaYfNyqOv8XOtcF2YkenAiPjK/MzsIbObhwicDtREd7Br7ZArBm+GL+c5NQ3e8+gPrt1podg1ldZMbZHAi29vM974etXODsnpA3shIMplVsyxwie4PvgfP1avkeHMuPpflPFX6PrJOWatZvIHLfGqSP/rM51HDgO5xcZ0qDTJOvj7Ko0GHfn0CoWzKhwGrZ1ioRDKmTipFhiqFq7iYLts5eMB03W4m62l2Pxpzbs5ugRC49YtWmvAcbVFzERQg2GlB0/slkSdIwdxGqh8Ec3Ma/vpGNkghBBu/hhC3EladFaHPjcp7jlItW7ktyndikBV1cim95rJWWmuGxk8fOdAEVBuPV0sOx+6AwOSfM+o8Pxbe3Vjqv2UHxmMOLlPBs3uTfeS4awUuRY3oizBxaok+H8XWXMP91CjNStRnPWWIOZGG57QtMDOJiqwdwLENVEasAguwfoKSO2tUToLfHPZxtW86rfoGoX1oQ+JiebONxO5bvony8zqtcCt6s3KesKsQeJJHmfaItxylsQyi072PeDPmVuZDgDSx3C31NCYI=
after_script:
- echo $TRAVIS_BUILD_DIR
- eval "$(ssh-agent -s)"
- traceroute -p 22 149.56.44.225
- sshpass -e scp ./ScadaBR.war test@149.56.44.225:/home/test/ScadaBR.war
- sshpass -e scp ./ScadaLTS-UI/war/ScadaLTS.war test@149.56.44.225:/home/test/ScadaLTS.war