addons:
  ssh_known_hosts: 149.56.44.225
before_install:
  - sudo apt-get install tomcat7
  - sudo apt-get install traceroute
  - openssl aes-256-cbc -K $encrypted_5880cf525281_key -iv $encrypted_5880cf525281_iv -in deploy_rsa.enc -out deploy_rsa -d
before_script:
  - npm install -g bower
  - chmod +x ./get_seroUtils.sh
  - "./get_seroUtils.sh"
  - cd ./WebContent/resources/app; bower update;
  - cd ../../..
language: java
jdk:
  - openjdk7
script: ant war
branches:
  only:
  - "/^PROC-.*$/"
notifications:
  email: false
env:
  matrix:
  - CATALINA_HOME=/usr/share/tomcat7
after_script:
  - echo $TRAVIS_BUILD_DIR
before_deploy:
  - eval "$(ssh-agent -s)"
  - traceroute -p 22 149.56.44.225
  - chmod 600 $TRAVIS_BUILD_DIR/deploy_rsa
  - ssh-add $TRAVIS_BUILD_DIR/deploy_rsa
deploy:
    provider: script
    skip_cleanup: true
    script: scp ./ScadaBR.war root@149.56.44.225:/root/ScadaBR.war