before_install:
- sudo apt-get install tomcat7
- sudo apt-get install sshpass
before_script:
- npm install -g bower
- chmod +x ./get_seroUtils.sh
- "./get_seroUtils.sh"
- cd ./WebContent/resources/app; bower update;
- cd ../../..
language: java
jdk:
- openjdk7
script: ant war
branches:
  only:
  - "/^PROC-.*$/"
notifications:
  email: false
env:
  matrix:
  - CATALINA_HOME=/usr/share/tomcat7
  global:
    secure: qvmXYZpp4o1YeG8CdA+HsBHH10q97MZgpU6X9vcDfdgi9gN9gmYuFwmGvoxR1JbmEbLuDvpNbMGEVNHWDTuO8qQA0ua5f3zMl5b8ucjwLnNNQYTMfXw1kHKygbcjCz8fFCVcIZUhqFRm65xUv6CIOPTFtZQ5Gz6cvmexTCQ+oviYlYR24TXqstjG4z10+4rjdt5xTtdNoz4I7uVU0a2uI7PbAiHtw2DSpK+l9y/k47f++xG9aGH3o5aOwMuFJHFwmDIwx97/vfIu88Cz7tTnyFT95dTHPVNcpOFIhu3LeoRaxMKMp0VFqHoFPtOBLB/L7J+V5vO6DvWWsif6FHrwOMlOFo+ZKgGAtgRxML5VFUzUcrt7pKl/AZ0jEkp5EXbPFKgLNspV6mcHgGg9pqE8R/p0efuajC2pspWmpxcQN3kjMHNWeqIJzXQ/co1NQ2IHg1VqJ3soSv1Uh/BWwRtzaGP4A7ozv963aDkAU4SFyucoFKr4YHeHwE3yqybt12aa8FP36dyqQOpQzzTvDYxJkde+aYCGLMJqub7b2nM6ncCEbbCpIpNkakSwZb1H9Iqkzg09u2gM/keoiPmorrmvByJvErRRHwbWmWVswODvdGvJ5Mwbunjzzr7n0j3/bBgJXAbJ5ejd2vQbpSvG/9x/UOBCYmn5vq4m0q4vI4ZH2Fc=
after_success:
- echo $VS_RUN
